version: "3.7"
services:
  app:
    build: .
    container_name: pdf-esignature-server
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      profile: prod
      db_pass: pass
      AWS_ACCESS_KEY_ID: foobar
      AWS_SECRET_ACCESS_KEY: foobar
  db:
    image: postgres:9.6-alpine
    container_name: pdf-esignature-server-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: goxygen
      POSTGRES_DB: goxygen
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
  s3:
    image: localstack/localstack
    container_name: pdf-esignature-server-s3
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock' 
